services:
  database:
    container_name: travel_database
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
  phpMyadmin:
    image: phpmyadmin
    container_name: travel-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: admin
